#!/bin/bash
#startup script

CONFIG="/etc/ssh/sshd_config"

yum update
yum upgrade
yum install openssh-server

ssh-keygen
#ssh-copy-id username@serverip
#make sshd_config and add settings

{
echo 'PermitRootLogin no'
echo 'PasswordAuthentication no'
echo 'PubkeyAuthentication yes'
echo 'ChallengeResponseAuthentication no'
} >$CONFIG

systemctl reload sshd

firewall-cmd -permanent --add-service=ssh
systemctl restart firewalld.service
firewall-cmd --list-services
