#!/bin/bash
#startup script

CONFIG="/etc/ssh/sshd_config"

apt-get update
apt-get upgrade
#apt-get install openssh-server

ssh-keygen
#ssh-copy-id username@serverip
#make sshd_config and add settings

{
echo 'PasswordAuthentication no'
echo 'PubkeyAuthentication yes'
echo 'ChallengeResponseAuthentication no'
} >$CONFIG

systemctl reload sshd

ufw allow OpenSSH
ufw enable
ufw status
